[phases.setup]
aptPkgs = ["git", "curl", "unzip", "xz-utils", "python3", "python3-pip", "gcc"]

[phases.build]
cmds = [
  "git clone https://github.com/flutter/flutter.git /flutter",
  "export PATH=\"$PATH:/flutter/bin\" && flutter --version && flutter config --enable-web && flutter build web",
  "pip install -r requirements.txt"
]

[start]
cmd = "python signlanguage/python_model/inference_classifier.py"