
[phases.setup]
aptPkgs = [
    "git", 
    "curl", 
    "unzip", 
    "xz-utils", 
    "python3", 
    "python3-pip", 
    "gcc",
    "libgl1-mesa-glx",  # This provides libGL.so.1
    "libglib2.0-0", 
    "libsm6", 
    "libxext6", 
    "libxrender-dev",
    "libgl1",           # Additional OpenCV dependency
    "libglib2.0-0",     # Additional OpenCV dependency
    "libsm6",           # Additional OpenCV dependency
    "libxrender1",      # Additional OpenCV dependency
    "libxext6",         # Additional OpenCV dependency
    "libx11-6",         # Additional OpenCV dependency
    "libavcodec-dev",   # For video processing
    "libavformat-dev",  # For video processing
    "libswscale-dev"    # For video processing
]

[phases.build]
cmds = [
  "git clone https://github.com/flutter/flutter.git /flutter",
  "cd /app/signlanguage && /flutter/bin/flutter --version",
  "cd /app/signlanguage && /flutter/bin/flutter config --enable-web",
  "export PATH=\"$PATH:/flutter/bin\" && flutter --version && flutter config --enable-web && flutter build web",
  "cd /app/signlanguage && /flutter/bin/flutter build web",
  "pip install -r requirements.txt",
  "pip install opencv-python-headless"  # Use headless version for server environments
]

[start]
cmd = "python signlanguage/python_model/inference_classifier.py"